### ISSUE TITLE
Add ability to read Jacobians to Radiance class

### ISSUE THREAD

**Issue by ADCollard** [kevindougherty-noaa/PyGSI#90]
[pyGSI/diags.py](https://github.com/ADCollard/PyGSI/blob/develop/pyGSI/diags.py) does not have the ability to read in two-dimensional arrays from the netCDF diag files.

I have created the ability to read in the Jacobian files that are currently an optional output from GSI.

Details are in PyGSI pull request #89

**Comment by CoryMartin-NOAA** [comment]
Closed by PR #89
